---
site_name: "thing-description-schema"
docs_dir: resources/gens/docs/ontology/

theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Index: index.md
site_url: https://github.io/w3c/wot-thing-description-toolchain-tmp
repo_url: https://github.com/w3c/wot-thing-description-toolchain-tmp


