name: Deploy Thing Description Specification to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      DOCS_OUTPUT_PATH: resources/gens

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies using UV
        run: |
          pip install uv
          uv pip install -e . --system

      - name: Generate Thing Description Specification
        run: |
          wotis generate-wot-resources -d

      - name: Upload Generated Artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          name: wotis-generated-docs
          path: ${{ env.DOCS_OUTPUT_PATH }}
          
