# Built from:
# https://docs.github.com/en/actions/guides/building-and-testing-python
---
name: Build and test thing_description_schema

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        py: ["3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run the program
        run: uv run -p ${{ matrix.py }} wotis
